// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIiknMc0qgqWv-jkrL-QWfYajxPMiZ-PE',
    appId: '1:154343574684:web:0adcd887c6afe9f8767159',
    messagingSenderId: '154343574684',
    projectId: 'ea-flutter-test-app',
    authDomain: 'ea-flutter-test-app.firebaseapp.com',
    storageBucket: 'ea-flutter-test-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbXFwhKMFeuKmXn4xFAm65Bcqj1npHJvc',
    appId: '1:154343574684:android:ebede899cb662f33767159',
    messagingSenderId: '154343574684',
    projectId: 'ea-flutter-test-app',
    storageBucket: 'ea-flutter-test-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu7TNgQTIgx2objSZRra6y4Bmnl0_spM8',
    appId: '1:154343574684:ios:41e0d67a8a03cf7a767159',
    messagingSenderId: '154343574684',
    projectId: 'ea-flutter-test-app',
    storageBucket: 'ea-flutter-test-app.appspot.com',
    iosClientId: '154343574684-419s6shrd5uv4o57lrr3lethij3fnj80.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu7TNgQTIgx2objSZRra6y4Bmnl0_spM8',
    appId: '1:154343574684:ios:66072bb057818c61767159',
    messagingSenderId: '154343574684',
    projectId: 'ea-flutter-test-app',
    storageBucket: 'ea-flutter-test-app.appspot.com',
    iosClientId: '154343574684-ibp8t1nmsag1cru3qttt8evo7j3dsvc6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTestApp.RunnerTests',
  );
}
