# Uncomment this line to define a global platform for your project
# platform :ios, '11.0'

# Uncomment this line if you want to disable IDFA collection
# $FirebaseAnalyticsWithoutAdIdSupport = true
# More details:
# - https://firebase.google.com/docs/analytics/configure-data-collection?platform=ios#disable-IDFA-collection
# - https://firebase.flutter.dev/docs/analytics/get-started/#optional-disable-idfa-tracking
# - https://pub.dev/packages/firebase_analytics/versions/8.3.4#ios-app-tracking-transparency
# - https://github.com/firebase/flutterfire/blob/338e6d7c924e6f79c9bc6925171f8088f16233cc/packages/firebase_analytics/firebase_analytics/ios/firebase_analytics.podspec#L7 

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

pod 'GoogleTagManager'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end